### ISSUE TITLE
NavbarItem not SEO friendly (no title attribute)

### ISSUE THREAD

**Issue by jack-y** [elcobvg/svelte-bulma-components#2]
SEO optimization needs the title attribute in the `<a>` tags.
Is there a way to add this title attribute to the NavbarItem component?

**Comment by elcobvg** [comment]
At the moment not, no. However, as soon as I have some time, I plan to update the components to Svelte 3 and then I'll add the title attribute. Thanks for the tip.

**Comment by jack-y** [comment]
Thanks for your great job.
